# -*- coding: utf-8 -*-
"""YOLOv4_B10802217.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11BpV94TwKssipNXQ90LR1XkZUQHheM6g
"""

! nvidia-smi

! git clone https://github.com/AlexeyAB/darknet.git

! head darknet/Makefile

! sed -i "s/GPU=0/GPU=1/g" /content/darknet/Makefile
! sed -i "s/CUDNN=0/CUDNN=1/g" /content/darknet/Makefile
! sed -i "s/OPENCV=0/OPENCV=1/g" /content/darknet/Makefile

! head darknet/Makefile

! cd darknet; make

! cd darknet ; ./darknet

! gdown https://drive.google.com/uc?id=1cewMfusmPjYWbrnuJRuKhPMwRe_b9PaT

! ls darknet/data

from PIL import Image
Image.open('darknet/data/scream.jpg')

! cd darknet; ./darknet detect /content/darknet/cfg/yolov4.cfg  /content/yolov4.weights /content/darknet/data/scream.jpg

from PIL import Image
Image.open('/content/darknet/predictions.jpg')

from PIL import Image
Image.open('darknet/data/ETERNALS.jpg')

! cd darknet; ./darknet detect /content/darknet/cfg/yolov4.cfg  /content/yolov4.weights /content/darknet/data/ETERNALS.jpg

from PIL import Image
Image.open('/content/darknet/predictions.jpg')

from PIL import Image
Image.open('darknet/data/People_dog.jpg')

! cd darknet; ./darknet detect /content/darknet/cfg/yolov4.cfg  /content/yolov4.weights /content/darknet/data/People_dog.jpg

from PIL import Image
Image.open('/content/darknet/predictions.jpg')